Add extra initializers to Nimbus objects
mozilla/application-services pull request #3991
Opened 2021-03-25 18:42 UTC by jhugman

This is followup work to [SDK-208][1], in order to be usable from Firefox for iOS (the work of [SDK-210][2]).

[1]: https://jira.mozilla.com/browse/SDK-208
[2]: https://jira.mozilla.com/browse/SDK-210

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `automation/all_tests.sh` runs to completion and produces no failures
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

2021-03-25 20:58 UTC, travis79 requested changes
I'm not sure why the `public init`'s were added, can you help me understand what you are trying to accomplish?

2021-03-25 20:58 UTC, travis79 commented on components/nimbus/ios/Nimbus/NimbusApi.swift
> +    }
This `init` is provided for free by Swift and shouldn't be required, just having the public memebers defined should be enough.

2021-03-25 20:58 UTC, travis79 commented on components/nimbus/ios/Nimbus/NimbusApi.swift
> +    public let channel: String
These are both public by default since the struct is `public`, so I think `public` modifiers on the struct members is redundant.

2021-03-25 20:58 UTC, travis79 commented on components/nimbus/ios/Nimbus/NimbusApi.swift
> +    }
Same comment about getting the `init` for free from Swift, I don't understand why this is necessary if the struct is already declared public?

2021-03-25 20:58 UTC, travis79 commented on components/nimbus/ios/Nimbus/NimbusApi.swift
> +    public let url: URL
Same comment as before, this defaults to public if the struct is public.

2021-03-26 16:21 UTC, travis79 commented
See "Memberwise Initializers for Structure Types" here: https://docs.swift.org/swift-book/LanguageGuide/Initialization.html

2021-03-26 16:30 UTC, travis79 commented on components/nimbus/ios/Nimbus/NimbusApi.swift
> +    public let channel: String
I take this one back, the default modifier in Swift is `internal` so maybe `public` is needed.

2021-03-26 16:31 UTC, travis79 commented on components/nimbus/ios/Nimbus/NimbusApi.swift
> +    public let url: URL
Retracted, default access is `internal` so `public` here makes sense.

2021-03-26 18:43 UTC, travis79 approved these changes
👍 from me after our conversation (and trying it out without the `public init`)

2021-03-26 18:52 UTC, jhugman commented
For context for archivists:

From the Swift Book chapter on [Access Control][1]:

> The default memberwise initializer for a structure type is considered private if any of the structure’s stored properties are private. Likewise, if any of the structure’s stored properties are file private, the initializer is file private. Otherwise, the initializer has an access level of internal.
>
> As with the default initializer above, if you want a public structure type to be initializable with a memberwise initializer when used in another module, you must provide a public memberwise initializer yourself as part of the type’s definition.

We had a similar problem with this in uniffi.

[1]: https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID21

2021-03-26 18:52 UTC, merged

2021-03-26 21:03 UTC, travis79 commented
> For context for archivists:
> 
> From the Swift Book chapter on [Access Control](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID21):
> 
> > The default memberwise initializer for a structure type is considered private if any of the structure’s stored properties are private. Likewise, if any of the structure’s stored properties are file private, the initializer is file private. Otherwise, the initializer has an access level of internal.
> > As with the default initializer above, if you want a public structure type to be initializable with a memberwise initializer when used in another module, you must provide a public memberwise initializer yourself as part of the type’s definition.
> 
> We had a similar problem with this in uniffi.

TIL, thanks!