FML: Generate Kotlin from FML intermediate representation
mozilla/application-services pull request #4607
Opened 2021-10-25 19:15 UTC by jhugman

As part of [SDK-419][1].

[1]: https://mozilla-hub.atlassian.net/browse/SDK-419

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

2021-11-01 12:02 UTC, jhugman reviewed
Self-review.

2021-11-01 20:59 UTC, tarikeshaq requested changes
There are still some bits I need to go over and review (all the templates and some of the `gen_structs` files), but I timeboxed and I'll move on to other things and come back to this tomorrow

My `Request Changes` is specifically for the comment on testing (i.e the requirement that kotlinc is installed for tests to pass which impacts everyone working on AS)

The change is **large**, I do wonder if it's possible to get something smaller that works landed, I know we took the pattern (and most the code) from `uniffi` and the pattern there is complete, but I feel a little iffy landing something this big quickly.. I'm not opposed to it, we can always iterate, but I want to make sure we give it the level of depth in review it deserves

Anyways, I'll come back for a second round tomorrow morning

2021-11-01 20:59 UTC, tarikeshaq commented on components/support/nimbus-fml/src/backends/kotlin/mod.rs
> +pub(crate) fn generate_struct(
Feel free to completely ignore this - just jotting down what I'm thinking - I don't know how I feel about the name `generate_struct`, it's mostly the `struct` part that feels weird to me... Not a very constructive thought, I'm not sure what the best alternative is

2021-11-01 20:59 UTC, tarikeshaq commented on components/support/nimbus-fml/src/backends/kotlin/templates/FeatureManifestTemplate.kt
> +{% import "macros.kt" as kt %}
Do we need this import here since we don't use any macros in the rest of the template, or are you protecting future uses of macros?

2021-11-01 20:59 UTC, tarikeshaq commented on components/support/nimbus-fml/src/backends/kotlin/gen_structs/mod.rs
> +impl<'a> FeatureManifestDeclaration<'a> {
Should `FeatureManifestDeclaration` `impl` `CodeDeclaration`?

2021-11-01 20:59 UTC, tarikeshaq commented on components/support/nimbus-fml/src/backends/kotlin/gen_structs/object.rs
> +impl CodeDeclaration for ObjectRuntime {}
Do we need this struct and impl? I see it use commented out in the `mod.rs`

2021-11-05 19:29 UTC, tarikeshaq approved these changes
Awesome! Thank you for making sure that other A-S devs aren't affected by this 🙏 Since I'm out next week feel free to land this whenever you feel it's ready

2021-11-05 19:29 UTC, tarikeshaq commented on publish.gradle
> +            commandLine '/usr/bin/env', 'cargo', 'uniffi-bindgen', 'generate', "${project.projectDir}/${udlFilePath}", '--language', 'kotlin', '--out-dir', "${buildDir}/${uniffiGeneratedPath}"
Oh! Curious what we needed this change for

2021-11-05 19:29 UTC, tarikeshaq commented on components/support/nimbus-fml/src/backends/kotlin/mod.rs
> +        if !detect_kotlinc()? {
Nice! FWIW the `println!` won't be seen on `cargo test` since cargo test defaults to catching `stdout` but that's OK for now!

2021-11-05 19:29 UTC, tarikeshaq commented on components/support/nimbus-fml/src/backends/kotlin/mod.rs
> +        let output = Command::new("which").arg("kotlinc").output()?;
I'm trying to remember if our tests run in any non-unix environment (or any environment without the `which` command) but I think we should be okay!

2021-11-06 14:27 UTC, merged