Bug 1820927 - Update Glean to v52.4.0
mozilla/application-services pull request #5426
Opened 2023-03-09 19:47 UTC by travis79

This fixes a cargo audit vuln in the Glean dependency `remove_dir_all`

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

2023-03-09 22:44 UTC, tarikeshaq requested changes
Thanks @travis79!! 

We should probably also bump the iOS dependency (by bumping the version in Xcode)

Also, if we'd like to fully fix the `remove_dir_all` advisory in application-services, we should run:
```sh
$ cargo update -p tempfile
```

`tempfile` has a dependency on the affected version, so updating that and landing the `Cargo.lock` changes should fix the CI here!

2023-03-10 15:03 UTC, travis79 commented
> Thanks @travis79!!
> 
> We should probably also bump the iOS dependency (by bumping the version in Xcode)
> 
> Also, if we'd like to fully fix the `remove_dir_all` advisory in application-services, we should run:
> 
> ```shell
> $ cargo update -p tempfile
> ```
> 
> `tempfile` has a dependency on the affected version, so updating that and landing the `Cargo.lock` changes should fix the CI here!

yeah yeah, I know....  😅   I found this out myself a little late. I'm getting a new release today.

2023-03-10 18:04 UTC, travis79 commented
> `During handling of the above exception, another exception occurred:`

2023-03-10 20:05 UTC, travis79 commented
@tarikeshaq this is ready for a re-review whenever you get a chance.

2023-03-10 20:20 UTC, rvandermeulen commented on build.gradle
> +        glean_version = '52.4.0'
Should this be 52.4.1 now?

2023-03-10 20:22 UTC, travis79 commented on build.gradle
> +        glean_version = '52.4.0'
Yeah...  it should.

2023-03-10 20:43 UTC, tarikeshaq approved these changes
This LGTM! one thing we should do before landing is update the iOS dependency too in https://github.com/mozilla/application-services/blob/e27985157b0e664fcd14bd182eace1ce55720760/megazords/ios-rust/MozillaTestServices/MozillaTestServices.xcodeproj/project.pbxproj#L1029

(updating through Xcode is good enough)

I'm not blocking on it because that version is mostly only used for development and local tests 😄

2023-03-10 20:59 UTC, travis79 commented
> This LGTM! one thing we should do before landing is update the iOS dependency too in
> 
> https://github.com/mozilla/application-services/blob/e27985157b0e664fcd14bd182eace1ce55720760/megazords/ios-rust/MozillaTestServices/MozillaTestServices.xcodeproj/project.pbxproj#L1029
> 
> (updating through Xcode is good enough)
> 
> I'm not blocking on it because that version is mostly only used for development and local tests 😄

Might as well get it while I'm here, please stand by :)

2023-03-10 21:20 UTC, merged