[WIP] Refactored webext-storage database close function
mozilla/application-services pull request #6424
Opened 2024-10-21 23:02 UTC by lougeniaC64

This is so not ready for primetime . . . enter at your own risk.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due diligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

2024-10-27 06:58 UTC, linabutler requested changes
know this is still in draft, but I wanted to leave a bit of feedback to unblock you. This is looking great, @lougeniaC64; thanks again for making all those changes! This sets us up for adding the shutdown blocker in Firefox, and then we can re-land your Firefox patch and close the chapter on this migration!

I’m requesting changes specifically for `WebExtStorageStore::close`: I don’t think the `Arc::try_unwrap(self.db.clone())` is going to do what we want. Everything else looks great, though, including the switch to `.unchecked_transaction()`.

2024-11-01 17:56 UTC, lougeniaC64 commented on components/webext-storage/src/api.rs
> +        let tx = conn.unchecked_transaction()?;
I was wondering about this. I generally don't like to change tests during refactors. Thanks for the clarification.

2024-11-01 18:30 UTC, lougeniaC64 commented on components/webext-storage/src/store.rs
> +        let shared: ThreadSafeStorageDb = match Arc::try_unwrap(self.db.clone()) {
I think I was attempting to optimize ahead of time for the forthcoming uniffication PR, but I think I'll keep whatever's required to expose the close function contained in that PR. For now I'll just replace `try_unwrap` with `into_inner`.

2024-11-12 19:12 UTC, linabutler approved these changes
Ship it!

2024-11-12 19:49 UTC, merged