Bug 1930969 - Implement remaining environment matching in the search engine selector
mozilla/application-services pull request #6500
Opened 2024-11-28 16:30 UTC by Standard8

This implements the remaining environment matching in the search engine selector. This also gets the desktop `test_engine_selector_environment.js` passing.

Note that we do not add support for `optional` here, as that isn't really an environment variable and should be handled by the application itself according to what it does.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [X] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [X] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [X] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due diligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

2024-12-03 00:15 UTC, linabutler approved these changes
Looks great to me; thank you!

2024-12-03 00:15 UTC, linabutler commented on components/search/src/environment_matching.rs
> +    env_value.is_empty() || env_value.contains(user_value)
Nice use of the `PartialEq` trait bound here!

If you want to get a little fancier—or if you find yourself wanting more generic slice methods like this in the future—you can make an [extension trait](http://xion.io/post/code/rust-extension-traits.html), and have all slices implement it:

```rust
use std::cmp::PartialEq;

trait SliceExt<T: ?Sized> {
    fn is_empty_or_contains(&self, value: &T) -> bool where T: PartialEq;
}

impl<T> SliceExt<T> for [T] {
    fn is_empty_or_contains(&self, value: &T) -> bool where T: PartialEq {
        self.is_empty() || self.contains(value)
    }
}
```

Then, you could use it like this:

```rust
environment.channels.is_empty_or_contains(&user_environment.update_channel)
    && environment.applications.is_empty_or_contains(&user_environment.app_name)
    && environment.device_type.is_empty_or_contains(&user_environment.device_type)
```

And, if you wanted to use your extension methods in multiple modules, you could put the trait inside a separate module—let's say `ext.rs`—and import it into your other modules like any other item:

```rust
use crate::ext::SliceExt;
```

2024-12-03 00:15 UTC, linabutler commented on components/search/src/environment_matching.rs
> +                    ..Default::default()
Great!

2024-12-04 18:18 UTC, linabutler commented on components/search/src/environment_matching.rs
> +fn matches_version(
I keep forgetting about `.map_or()` on [`Option`](https://doc.rust-lang.org/std/option/enum.Option.html#method.map_or) and [`Result`](https://doc.rust-lang.org/std/result/enum.Result.html#method.map_or)—updated to use that!

2024-12-05 19:49 UTC, mandysGit requested changes
Thanks for adding these in. It looks great! 
I really love the use of `..Default::default()`. It reads so nicely! 🤩 

I left comments for two of the tests that may need to be changed. The assertion doesn't seem to match the test statement.

2024-12-05 19:49 UTC, mandysGit commented on components/search/src/environment_matching.rs
>              "Should return false when the distribution does not match any in the environment"
If I'm reading this correctly, this one seems to be testing applications and not distributions.

2024-12-05 19:49 UTC, mandysGit commented on components/search/src/environment_matching.rs
> +            "Should return true when the distribution and region matches the environment"
This one also is not testing distribution. 

Suggesting to change it to:
"Should return true when the application and region matches the environment"

2024-12-05 19:49 UTC, mandysGit commented on components/search/src/environment_matching.rs
> +                    experiment: "warp-drive".to_string(),
TIL - Warp drive was a technology that allowed space travel at faster-than-light speeds. 😄

2024-12-11 23:38 UTC, mandysGit approved these changes
Thank you.

2024-12-12 10:29 UTC, merged